name: workflow

on:
  push:
    branches:
      - staging
      - main

jobs:
  check:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      # Setup Node.js
      - uses: actions/setup@v3
        with:
          node-version: "22"

      # Install dependencies
      - run: npm ci

      # Run ESLint
      - run: npm run lint

      # Run tests
      - run: npm test

  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: hw-authentication-app
      GCP_PROJECT_ID: heron-wellnest
      REGION: asia-southeast1
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

          # Install dependencies (needed for build)
      - run: npm ci

      # Build Docker image
      - run: docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .

      # Authenticate with GCP
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      # Push Docker image
      - run: docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA

      # Deploy to Cloud Run
      - run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
